import { useEffect, useRef, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { Bell, BookOpen, BrainCircuit, CalendarDays, ChevronDown, FileText, ImageUp, LayoutDashboard, LogOut, Menu, ScanEye, Search, Settings, Sparkles, Upload, UsersRound, X, Zap } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { supabase } from '../lib/supabase'
import logo from '../assets/images/drishti-logo.png'
import sidebarImage from '../assets/images/sidebar-image.png'
import '../styles/doctor-dashboard.css'

const navItems = [
  { label: 'Dashboard', icon: LayoutDashboard, path: '/dashboard' },
  { label: 'Analyze Image', icon: ScanEye, path: '/analysis' },
  { label: 'My Reports', icon: FileText, path: '/reports' },
  { label: 'Appointments', icon: CalendarDays, path: '/appointments' },
  { label: 'AI Insights', icon: BrainCircuit, path: '/insights' },
  { label: 'Knowledge Hub', icon: BookOpen, path: '/knowledge' },
]
const insights = [
  'Educational: consistent image quality checks help support reliable retinal screening workflows.',
  'Educational: explainable AI outputs are designed to support—not replace—clinical judgement.',
  'Educational: early screening can help clinicians identify referral needs sooner.',
]

function Sidebar({ open, onClose, onLogout, loggingOut, navigate }) {
  const item = (entry) => { const Icon = entry.icon; return <button key={entry.label} className={entry.path === '/dashboard' ? 'side-link active' : 'side-link'} onClick={() => { navigate(entry.path); onClose() }}><Icon size={19} />{entry.label}</button> }
  return <><AnimatePresence>{open && <motion.button className="sidebar-scrim" aria-label="Close navigation" onClick={onClose} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} />}</AnimatePresence><motion.aside className={`doctor-sidebar ${open ? 'is-open' : ''}`} initial={{ x: -18, opacity: 0 }} animate={{ x: 0, opacity: 1 }} transition={{ duration: .35 }}><div className="sidebar-top"><img src={logo} alt="Drishti AI" /><button className="mobile-close" aria-label="Close navigation" onClick={onClose}><X /></button></div><nav>{navItems.map(item)}</nav><div className="sidebar-bottom"><div className="sidebar-divider" /><button className="side-link" onClick={() => navigate('/settings')}><Settings size={19} />Settings</button><button className="side-link logout" onClick={onLogout} disabled={loggingOut}><LogOut size={19} />{loggingOut ? 'Logging out…' : 'Logout'}</button><img src={sidebarImage} alt="Drishti AI retinal care illustration" /></div></motion.aside></>
}

function AnalyzeCard({ navigate }) {
  const inputRef = useRef(null), [file, setFile] = useState(null), [dragging, setDragging] = useState(false), [message, setMessage] = useState('')
  const choose = (next) => { if (!next) return; if (!['image/jpeg', 'image/png'].includes(next.type)) { setMessage('Please choose a JPG or PNG image.'); return } if (next.size > 10 * 1024 * 1024) { setMessage('The image must be 10 MB or smaller.'); return } setFile(next); setMessage('Image selected. Secure upload and analysis will be enabled when the imaging backend is connected.') }
  return <section className="dashboard-card analyze-card"><div className="card-heading"><div><span className="card-icon"><ScanEye size={20} /></span><h2>Analyze Retinal Image</h2><p>Upload a fundus image to get AI-powered analysis and clinical insights.</p></div><button className="text-action" onClick={() => navigate('/knowledge')}>View Guidelines →</button></div><div className={`upload-zone ${dragging ? 'dragging' : ''}`} onDragOver={e => { e.preventDefault(); setDragging(true) }} onDragLeave={() => setDragging(false)} onDrop={e => { e.preventDefault(); setDragging(false); choose(e.dataTransfer.files?.[0]) }}><input ref={inputRef} type="file" accept="image/png,image/jpeg" onChange={e => choose(e.target.files?.[0])} /><ImageUp size={31} /><strong>{file ? file.name : 'Drag & drop your retinal image here'}</strong><span>{file ? `${Math.ceil(file.size / 1024)} KB selected` : 'JPG or PNG · Maximum file size 10 MB'}</span><button onClick={() => inputRef.current?.click()}><Upload size={16} /> Browse Files</button></div>{message && <p className="upload-message" role="status">{message}</p>}<div className="analyze-footer"><span>Secure, encrypted image handling will be available with the imaging service.</span><button className="primary-analysis" onClick={() => setMessage(file ? 'Analysis is not available yet. Connect the secure imaging API to enable it.' : 'Choose a JPG or PNG image before starting analysis.')}>Upload Image <span>→</span></button></div></section>
}

function RecentReports({ navigate }) { return <section className="dashboard-card reports-card"><div className="small-card-heading"><div><h2>Recent Reports</h2><p>Your latest completed analyses</p></div><button className="text-action" onClick={() => navigate('/reports')}>View All →</button></div><div className="empty-state"><FileText size={28} /><strong>No reports yet</strong><span>Your completed analyses will appear here.</span></div></section> }

function Insights({ navigate }) { const [index, setIndex] = useState(0); useEffect(() => { const timer = setInterval(() => setIndex(i => (i + 1) % insights.length), 5500); return () => clearInterval(timer) }, []); return <section className="dashboard-card insight-card"><div className="small-card-heading"><div><h2><BrainCircuit size={19} />AI Insights</h2><p>Educational workflow guidance</p></div><button className="text-action" onClick={() => navigate('/insights')}>View More →</button></div><div className="insight-message"><Sparkles size={24} /><AnimatePresence mode="wait"><motion.p key={index} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} transition={{ duration: .32 }}>{insights[index]}</motion.p></AnimatePresence></div><div className="insight-footer"><span className="dots">{insights.map((_, i) => <i key={i} className={i === index ? 'active' : ''} />)}</span></div></section> }

export default function DashboardPage() {
  const { user, profile } = useAuth(); const navigate = useNavigate(); const [drawer, setDrawer] = useState(false), [loggingOut, setLoggingOut] = useState(false)
  const rawName = profile?.full_name || user?.user_metadata?.full_name || user?.email?.split('@')[0] || 'Doctor'; const doctorName = rawName.replace(/^dr\.\s*/i, ''); const initials = doctorName.split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase()
  const logout = async () => { setLoggingOut(true); await supabase?.auth.signOut(); navigate('/login', { replace: true }) }
  const stats = [{ label: 'Images Analyzed', icon: ImageUp }, { label: 'Reports Generated', icon: FileText }, { label: 'Appointments', icon: CalendarDays }, { label: 'Diagnosis Accuracy', icon: Sparkles }]
  return <main className="doctor-dashboard"><Sidebar open={drawer} onClose={() => setDrawer(false)} onLogout={logout} loggingOut={loggingOut} navigate={navigate} /><div className="dashboard-shell"><header className="dashboard-header"><button className="header-menu" aria-label="Open navigation" onClick={() => setDrawer(true)}><Menu size={21} /></button><label className="dashboard-search"><Search size={18} /><input placeholder="Search reports, cases, or anything..." aria-label="Search reports, cases, or anything" /></label><div className="header-profile"><button className="notification" aria-label="Notifications"><Bell size={20} /></button><div className="doctor-avatar">{initials}</div><div><strong>Dr. {doctorName}</strong><span>Ophthalmologist</span></div><ChevronDown size={17} /></div></header><div className="dashboard-content"><motion.section className="welcome" initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }}><div><p>DOCTOR DASHBOARD</p><h1>Welcome back, Dr. <em>{doctorName}</em></h1><span>Your expertise makes a difference. Let’s keep building healthier vision.</span></div><aside className="welcome-callout"><UsersRound size={25} /><strong>Better Diagnostics.<br />Brighter Futures.</strong></aside></motion.section><section className="stat-grid">{stats.map(({ label, icon: Icon }, index) => <motion.article key={label} className="stat-card" initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .08 * index }}><span><Icon size={19} /></span><p>{label}</p><strong>—</strong><small>No data yet</small></motion.article>)}</section><section className="dashboard-grid"><AnalyzeCard navigate={navigate} /><RecentReports navigate={navigate} /><section className="dashboard-card quick-card"><div className="small-card-heading"><div><h2><Zap size={18} />Quick Actions</h2><p>Continue your clinical workflow</p></div></div><div className="quick-actions">{[{ label: 'New Analysis', icon: ScanEye, path: '/analysis' }, { label: 'View Reports', icon: FileText, path: '/reports' }, { label: 'Manage Appointments', icon: CalendarDays, path: '/appointments' }, { label: 'Knowledge Hub', icon: BookOpen, path: '/knowledge' }].map(({ label, icon: Icon, path }) => <button key={label} onClick={() => navigate(path)}><Icon size={18} />{label}<span>→</span></button>)}</div></section><Insights navigate={navigate} /></section><motion.aside className="dashboard-quote" initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: .35 }}>“Early detection saves vision. AI helps you see it sooner.” <span>— Drishti AI</span></motion.aside></div></div></main>
}
